'use strict';
/*
 * 🧬 MeR~NeL — commands/core/xmenu.js
 * Menu officiel — organisation exacte (toutes les commandes).
 */

module.exports = {
  name: 'xmenu',
  description: 'Affiche le menu complet de MeR~NeL',
  usage: 'Xmenu',
  category: 'menu',
  aliases: ['xhelp', 'help'],
  adminOnly: false,
  cooldownMs: 4000,
  run: async (ctx) => {
    const b = ctx.fmt.bold;
    const body = [
      '🧬 ' + b('𝗠𝗲𝗥~𝗡𝗘𝗟') + ' 🫟',
      '━━━━━━━━━━━━━━',
      '',
      '🧠 ' + b('𝗜𝗻𝘁𝗲𝗹𝗹𝗶𝗴𝗲𝗻𝗰𝗲 & 𝗖𝗵𝗮𝘁'),
      '├ ' + b('𝗫𝗰𝗵𝗮𝘁') + ' — discussion auto on/off',
      '├ ' + b('𝗫𝗮𝘀𝗸') + ' — question rapide à l’IA',
      '├ ' + b('𝗫𝗮𝗶') + ' — IA avancée',
      '├ ' + b('𝗫𝗮𝗻𝗶𝗺𝗲') + ' — fiche wiki d’un animé',
      '├ ' + b('𝗫𝗽𝗼𝗹𝗶𝗰𝗲') + ' — 20 polices de texte',
      '└ ' + b('𝗫𝗶𝗻𝗳𝗼'),
      '',
      '💰 ' + b('𝗘́𝗰𝗼𝗻𝗼𝗺𝗶𝗲'),
      '├ ' + b('𝗫𝗱𝗮𝗶𝗹𝘆') + ' — 350 XCoins / 24 h',
      '├ ' + b('𝗫𝗰𝗼𝗶𝗻𝘀'),
      '├ ' + b('𝗫𝗽'),
      '└ ' + b('𝗫𝗿𝗮𝗻𝗸') + ' — classement du groupe',
      '',
      '🎮 ' + b('𝗝𝗲𝘂𝘅'),
      '├ ' + b('𝗫𝗾𝘂𝗶𝘇') + ' — quiz groupe 5 catégories',
      '├ ' + b('𝗫𝗶𝗱') + ' — quiz manga (images)',
      '├ ' + b('𝗫𝗳𝗼𝗼𝘁') + ' — quiz foot (photos)',
      '├ ' + b('𝗫𝗱𝘂𝗲𝗹') + ' — duel 1v1 avec mise',
      '├ ' + b('𝗫𝗯𝗲𝘁') + ' — paris football réels',
      '├ ' + b('𝗫𝘀𝗹𝗼𝘁𝘀') + ' 🎰 machine à sous (×25 max)',
      '├ ' + b('𝗫𝗽𝗶𝗹𝗲') + ' 🪙 pile ou face (×2)',
      '├ ' + b('𝗫𝗰𝗼𝘂𝗿𝘀𝗲') + ' 🏇 course de chevaux (×3.5)',
      '├ ' + b('𝗫𝗿𝗽𝘀') + ' ✂️ pierre-feuille-ciseaux',
      '└ ' + b('𝗫𝗴𝗮𝗺𝗲') + ' — catalogue',
      '',
      '🖼️ ' + b('𝗠𝗲́𝗱𝗶𝗮𝘀'),
      '├ ' + b('𝗫𝗶𝗺𝗴') + ' — génération d’images (max 5)',
      '├ ' + b('𝗫𝗽𝗹𝗮𝘆') + ' — audio ≤ 2 min',
      '└ ' + b('𝗫𝘃𝗶𝗱𝗲𝗼') + ' — vidéo ≤ 2 min',
      '',
      '👤 ' + b('𝗣𝗿𝗼𝗳𝗶𝗹'),
      '├ ' + b('𝗫𝗽𝗿𝗼𝗳𝗶𝗹') + ' — carte + photo de profil',
      '├ ' + b('𝗫𝗽𝘀𝗲𝘂𝗱𝗼') + ' — changer de pseudo',
      '└ ' + b('𝗫𝗹𝗼𝘃𝗲') + ' 💖 amour parfait (photos + cœur)',
      '',
      '📢 ' + b('𝗚𝗿𝗼𝘂𝗽𝗲'),
      '├ ' + b('𝗫𝘁𝗮𝗴 𝗮𝗹𝗹'),
      '└ ' + b('𝗫𝗮𝗻𝗻𝗼𝗻𝗰𝗲'),
      '',
      '🛡️ ' + b('𝗔𝗱𝗺𝗶𝗻'),
      '├ ' + b('𝗫𝗯𝗮𝗻') + ' / ' + b('𝗫𝘂𝗻𝗯𝗮𝗻'),
      '├ ' + b('𝗫𝗸𝗶𝗰𝗸') + ' / ' + b('𝗫𝗮𝗱𝗱'),
      '├ ' + b('𝗫𝗰𝗹𝗲𝗮𝗿') + ' — nettoie mes messages',
      '├ ' + b('𝗫𝗼𝗳𝗳') + ' / ' + b('𝗫𝘀𝘁𝗼𝗽') + ' — éteindre/rallumer ici',
      '└ ' + b('𝗫𝗿𝗲𝘀𝘁𝗮𝗿𝘁') + ' — redémarrer le bot',
      '',
      '⚙️ ' + b('𝗦𝘆𝘀𝘁𝗲̀𝗺𝗲'),
      '├ ' + b('𝗫𝘂𝗽𝘁') + ' — activité + capacités',
      '└ ' + b('𝗫𝗺𝗲𝗻𝘂'),
      '',
      '━━━━━━━━━━━━━━',
      ctx.fmt.pick([
        '⚡ ' + b('Tu demandes, j’analyse… et j’agis.'),
        '⚡ ' + b('Système rapide. Ne le surcharge pas.'),
        '⚡ ' + b('Écris simplement : je comprends le contexte.'),
      ]),
    ];
    await ctx.send(ctx.fmt.frame('📋 𝗠𝗘𝗡𝗨', body.join('\n')));
  },
};
